services:
  db:
    image: 'mysql:8.0'
    restart: 'always'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-moodle}
      - MYSQL_USER=${MYSQL_USER:-moodle}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Secret}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-Secret}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_data:/var/lib/mysql'
    container_name: newmoodle_db_1
    networks:
      - moodlenet

  moodle:
    image: 'moodlehq/moodle-php-apache:8.2'
    restart: 'always'
    ports:
      - '80:80'
    depends_on:
      - db
    volumes:
      - 'moodle_app:/var/www/html'
      - 'moodle_data:/var/www/moodledata'
    container_name: newmoodle_web_1
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=${MYSQL_DATABASE:-moodle}
      - MOODLE_DOCKER_DBUSER=${MYSQL_USER:-moodle}
      - MOODLE_DOCKER_DBPASS=${MYSQL_PASSWORD:-Secret}
      - MOODLE_DOCKER_WEB_HOST=localhost
    networks:
      - moodlenet

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    networks:
      - moodlenet
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-Secret}

volumes:
  mysql_data:
    driver: local
  moodle_app:
    driver: local
    name: newmoodle_moodle_app
  moodle_data:
    driver: local
    name: newmoodle_moodle_data

networks:
  moodlenet:
    driver: bridge
